### ISSUE TITLE
Additional recall methods

### ISSUE THREAD

**Issue by wasabipesto** [halomademeapc/ChatBeet#52]
# Additional recall methods

## Issue area
[ x ] General Rules
[ ] Stats
[ ] Personalization
[ ] WebUI
[ ] Other:  `[area]`

## Desired behavior
Ability to recall stored values via phrases in order to make commands feel more organic.

## Suggested command(s)
ChatBeet, what's astolfo?
ChatBeet, tell me about stabby miata
ChatBeet, show me ayaya
ChatBeet, when is Yato's birthday?
ChatBeet, what are my pronouns?
ChatBeet, what do you know about BODpc?

**Comment by halomakes** [comment]
adding alt command for all except: "ChatBeet, what are my pronouns?" because it overlaps with phrasing for recalling defs
