### ISSUE TITLE
SPEEDOMETER

### ISSUE THREAD

**Issue by blake-lowe** [halomademeapc/ChatBeet#77]
# [Summary]
A measure of how fast people are sending messages.

## Issue area
[X] General Rules
[ ] Stats
[ ] Personalization
[ ] WebUI
[ ] Other: 

## Desired behavior
Keep track of the rate messages are being sent in #dtella. It'd be cool to have a needle UI too, but not necessary. Including some ice, water, fire, etc. emoji in the chat output could be fun.

## Suggested command(s)
.cb speed
.cb chatrate
ChatBeet, how fast are we going?
* ```.cb [command] [argument]```
* ```ChatBeet, [do the thing]```

## Sample output
user: The current chat rate is 69 messages per minute.

**Comment by halomakes** [comment]
ooh this would be fun.  totally building a websocket needle in webui
